apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ccm-k8s-connectors
  title: CCM Kubernetes Connectors
  description: Enable CCM for a cluster by creating the necessary Kubernetes connectors
  tags:
    - solutions-factory
    - harness
    - ccm
    - connectors
spec:
  owner: group:default/harness_account_all_users # Defaults to all users
  type: setup
  parameters:
    - title: Cluster Information
      required:
        - delegate_name
        - enable_optimization
      properties:
        # The token property needs to be in the first page of the workflow
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        delegate_name:
          title: Delegate Name
          type: string
          description: Name of the delegate deployed in the cluster
        cluster_name:
          title: Cluster Name
          type: string
          description: Name of the cluster, if different from the delegate name
        cluster_description:
          title: Cluster Description
          type: string
        enable_optimization:
          title: Enable Optimization?
          description: If optimization (autostopping) should be enabled for this cluster (requires additional in-cluster deployment)
          type: boolean
          default: false
    - title: Solutions Factory Connection
      properties:
        solutions_factory_details:
          title: Solutions Factory Details
          type: object
          description: |
            ---
            Harness URL : <+variable.account.solutions_factory_endpoint>

            Harness Account : <+account.identifier>

            Solutions Factory Org : <+variable.account.solutions_factory_org>

            Solutions Factory Project : <+variable.account.solutions_factory_project>
          properties:
            harness_account_url:
              type: string
              default: <+variable.account.solutions_factory_endpoint>
              ui:widget: hidden
            harness_account_id:
              type: string
              default: <+account.identifier>
              ui:widget: hidden
            harness_org_id:
              type: string
              default: <+variable.account.solutions_factory_org>
              ui:widget: hidden
            harness_project_id:
              type: string
              default: <+variable.account.solutions_factory_project>
              ui:widget: hidden
            template_library_connector:
              type: string
              default: <+variable.account.solutions_factory_template_library_connector>
              ui:widget: hidden
            template_library_repo:
              type: string
              default: <+variable.account.solutions_factory_template_library_repo>
              ui:widget: hidden
            template_library_branch:
              type: string
              default: main
              ui:widget: hidden
  steps:
    - id: configure_workspace
      name: Configuring Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ parameters.solutions_factory_details.harness_project_id }}/pipelines/Create_and_Manage_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          GIT_REPOSITORY_CONNECTOR: ${{ parameters.solutions_factory_details.template_library_connector }}
          GIT_REPOSITORY_NAME: ${{ parameters.solutions_factory_details.template_library_repo }}
          GIT_REPOSITORY_BRANCH: ${{ parameters.solutions_factory_details.template_library_branch }}
          GIT_REPOSITORY_PATH: ccm-k8s-connectors
          RESOURCE_NAME: ccm_conn_${{ parameters.delegate_name|replace(" ","_") }}
          RESOURCE_OWNER: group:default/harness_account_all_users
          # YAML of Terraform variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS:
            delegate_name: ${{ parameters.delegate_name }}
            cluster_name: ${{ parameters.cluster_name }}
            description: ${{ parameters.cluster_description }}
            enable_optimization: ${{ parameters.enable_optimization }}
          # YAML of Terraform variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_SECRETS: {}
          # YAML of Environment variables of type 'String' mapped to their IDP parameters
          RESOURCE_VARS_ENVS: {}
          # YAML of Environment variables of type 'Secret' Reference mapped to their IDP parameters
          RESOURCE_VARS_ENVS_SECRET: {}
          # Should the workspace automatically include the default Harness Connector environment variables
          INCLUDE_HARNESS_ENVS: "true"
        apikey: ${{ parameters.token }}
        showOutputVariables: true
    - id: provision_workspace
      name: Provisioning your Harness Workspace
      action: trigger:harness-custom-pipeline
      input:
        url: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/all/orgs/${{ parameters.solutions_factory_details.harness_org_id }}/projects/${{ parameters.solutions_factory_details.harness_project_id }}/pipelines/Execute_IACM_Workspaces/pipeline-studio?storeType=INLINE
        inputset:
          workspace: ccm_conn_${{ parameters.delegate_name|replace(" ","_") }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Harness Workspace Configured - Execution Link
        url: ${{ steps.configure_workspace.output.PipelineUrl }}
      - title: Harness Workspace Provisioned - Execution Link
        url: ${{ steps.provision_workspace.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          kubernetes connector: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/module/ce/settings/connectors/${{ steps.provision_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.k8s_connector_id']}}

          ccm kubernetes connector: ${{ parameters.solutions_factory_details.harness_account_url }}/ng/account/${{ parameters.solutions_factory_details.harness_account_id }}/module/ce/settings/connectors/${{ steps.provision_workspace.output['pipeline.stages.Provision.spec.execution.steps.Provision.steps.apply.output.outputVariables.ccm_k8s_connector_id']}}
